/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Dao.DaoImpl.DepartmentDaoImpl;
import Dao.DepartmentDao;
import Model.Department;
import Model.Student;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haseeb
 */
public class DepartmentFrame extends javax.swing.JFrame {
    
    DepartmentDao departmentDao=new DepartmentDaoImpl();
    Integer departmentId=0;
    
    
    String columns[] = {"Department Id","Department Name", "Department Code"};
    DefaultTableModel departmentDefaultTableModel;
     private void fillstudentsTable(){
        departmentDefaultTableModel=new DefaultTableModel(columns,0);
        
        List<Department> getDepartments=departmentDao.getAllDepartments();
        for(Department d: getDepartments){
            
            Object row[]={d.getDptId(),d.getName(),d.getDptCode()};
            departmentDefaultTableModel.addRow(row);
        
            DepartmentDataTable.setModel(departmentDefaultTableModel);
        }
    }
      public void close(){
        WindowEvent closeWindow=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
        
    }
    private Department getDepartmentData(){
        String name=DepartmentNameField.getText();
        String code=DepartmentCodeField.getText();
        Department department=new Department();
        department.setName(name);
        department.setDptCode(code);
        return department;
    }
    private void clearFields(){
        DepartmentNameField.setText("");
        DepartmentCodeField.setText("");
    }
    
  



    /**
     * Creates new form DepartmentForm
     */
    public DepartmentFrame() {
        initComponents();
        fillstudentsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DepartmentCodeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DepartmentNameField = new javax.swing.JTextField();
        UpdateDepartmentBtn = new javax.swing.JButton();
        DepartmentAddBtn = new javax.swing.JButton();
        DepartmentDeleteBtn = new javax.swing.JButton();
        DepartmentClearBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        DepartmentDataTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("DEPARTMENT MANAGEMENT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Department Code");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Department Name");

        UpdateDepartmentBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateDepartmentBtn.setText("UPDATE");
        UpdateDepartmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDepartmentBtnActionPerformed(evt);
            }
        });

        DepartmentAddBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DepartmentAddBtn.setText("ADD");
        DepartmentAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentAddBtnActionPerformed(evt);
            }
        });

        DepartmentDeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DepartmentDeleteBtn.setText("DELETE");
        DepartmentDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentDeleteBtnActionPerformed(evt);
            }
        });

        DepartmentClearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DepartmentClearBtn.setText("CLEAR");
        DepartmentClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentClearBtnActionPerformed(evt);
            }
        });

        DepartmentDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        DepartmentDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepartmentDataTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(DepartmentDataTable);

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(DepartmentAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269)
                .addComponent(DepartmentDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(DepartmentClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(UpdateDepartmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DepartmentNameField)
                            .addComponent(DepartmentCodeField)))
                    .addComponent(jLabel1))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepartmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepartmentCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepartmentAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateDepartmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepartmentDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepartmentClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateDepartmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDepartmentBtnActionPerformed
        // TODO add your handling code here:
        Department department = this.getDepartmentData();
        department.setDptId(departmentId);
        boolean success = departmentDao.updateDepartment(department);
        if (success) {
            JOptionPane.showMessageDialog(this, "Updated Successfully");
           fillstudentsTable();
            clearFields();
        }
    }//GEN-LAST:event_UpdateDepartmentBtnActionPerformed

    private void DepartmentAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentAddBtnActionPerformed
        // TODO add your handling code here:
        boolean success=departmentDao.addDepartment(getDepartmentData());
        if(success){
            JOptionPane.showMessageDialog(this, "Added Successfully");
            fillstudentsTable();
            clearFields();
        }
    }//GEN-LAST:event_DepartmentAddBtnActionPerformed

    private void DepartmentDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentDeleteBtnActionPerformed
        // TODO add your handling code here:
        Department department = this.getDepartmentData();
        department.setDptId(departmentId);
         boolean success=departmentDao.deleteDepartment(departmentId);
        if(success){
            JOptionPane.showMessageDialog(this, "Deleted Successfully");
            fillstudentsTable();
            clearFields();
        }
    }//GEN-LAST:event_DepartmentDeleteBtnActionPerformed

    private void DepartmentClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentClearBtnActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_DepartmentClearBtnActionPerformed

    private void DepartmentDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartmentDataTableMouseClicked
        // TODO add your handling code here:
         departmentId = Integer.parseInt(DepartmentDataTable.getValueAt(DepartmentDataTable.getSelectedRow(), 0).toString());
         Department department=departmentDao.getDepartmentById(departmentId);
         DepartmentNameField.setText(department.getName());
         DepartmentCodeField.setText(department.getDptCode());
         
    }//GEN-LAST:event_DepartmentDataTableMouseClicked

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        close();
        MainMenu mainMenu=new MainMenu();
        mainMenu.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DepartmentAddBtn;
    private javax.swing.JButton DepartmentClearBtn;
    private javax.swing.JTextField DepartmentCodeField;
    private javax.swing.JTable DepartmentDataTable;
    private javax.swing.JButton DepartmentDeleteBtn;
    private javax.swing.JTextField DepartmentNameField;
    private javax.swing.JButton UpdateDepartmentBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
