/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import sun.awt.TimedWindowEvent;

/**
 *
 * @author Haseeb
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }
    
    public void close(){
        WindowEvent closeWindow=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        departmentManagementBtn = new javax.swing.JButton();
        studentManagementBtn = new javax.swing.JButton();
        coursestManagementBtn = new javax.swing.JButton();
        studenCoursestManagementBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("MAIN MENU");

        departmentManagementBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        departmentManagementBtn.setText("DEPARTMENT MANAGEMENT");
        departmentManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentManagementBtnActionPerformed(evt);
            }
        });

        studentManagementBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        studentManagementBtn.setText("STUDENT MANAGEMENT");
        studentManagementBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentManagementBtnMouseClicked(evt);
            }
        });
        studentManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentManagementBtnActionPerformed(evt);
            }
        });

        coursestManagementBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        coursestManagementBtn.setText("COURSES MANAGEMENT");
        coursestManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursestManagementBtnActionPerformed(evt);
            }
        });

        studenCoursestManagementBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        studenCoursestManagementBtn.setText("STUDENT-COURSE MANAGEMENT");
        studenCoursestManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studenCoursestManagementBtnActionPerformed(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logoutBtn.setText("LOGOUT");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(logoutBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(departmentManagementBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentManagementBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(coursestManagementBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(studenCoursestManagementBtn)
                        .addGap(116, 116, 116))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(departmentManagementBtn)
                .addGap(49, 49, 49)
                .addComponent(studentManagementBtn)
                .addGap(57, 57, 57)
                .addComponent(coursestManagementBtn)
                .addGap(52, 52, 52)
                .addComponent(studenCoursestManagementBtn)
                .addGap(50, 50, 50)
                .addComponent(logoutBtn)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void departmentManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentManagementBtnActionPerformed
        // TODO add your handling code here:
        close();
        DepartmentFrame departmentFrame=new DepartmentFrame();
        departmentFrame.setVisible(true);
        
        
    }//GEN-LAST:event_departmentManagementBtnActionPerformed

    private void studentManagementBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentManagementBtnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_studentManagementBtnMouseClicked

    private void studentManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentManagementBtnActionPerformed
        // TODO add your handling code here:
        close();
        StudentFrame studentFrame=new StudentFrame();
        studentFrame.setVisible(true);
    }//GEN-LAST:event_studentManagementBtnActionPerformed

    private void coursestManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursestManagementBtnActionPerformed
        // TODO add your handling code here:
         close();
         CoursesFrame coursesFrame=new CoursesFrame();
         coursesFrame.setVisible(true);
    }//GEN-LAST:event_coursestManagementBtnActionPerformed

    private void studenCoursestManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studenCoursestManagementBtnActionPerformed
        // TODO add your handling code here:
         close();
         StudentCourseManagementFrame studentCourseManagementFrame=new StudentCourseManagementFrame();
         studentCourseManagementFrame.setVisible(true);
    }//GEN-LAST:event_studenCoursestManagementBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
         close();
         LoginFrame loginFrame=new LoginFrame();
         loginFrame.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coursestManagementBtn;
    private javax.swing.JButton departmentManagementBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton studenCoursestManagementBtn;
    private javax.swing.JButton studentManagementBtn;
    // End of variables declaration//GEN-END:variables

   
}
